version: '3.1'
services:
  app:
    container_name: travel-assistant
    image: trip-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    links:
      - "postgres-service:postgres"
    networks:
      - app-db
    environment:
      - SERVER_PORT= 8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:5431/travel
    depends_on:
      - postgres-service
  postgres-service:
    image: postgres
    networks:
      - app-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: travel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
networks:
  app-db:
