spring:
  application:
    name: travel-assistant
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/external
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: travel-assistant-client
      principal-attribute: principal_username

#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8180/realms/external
#        registration:
#          keycloak:
#            client-id: travel-assistant-client
#            client-secret: 123123
#            scope: openid, profile, email
#            authorization-grant-type: authorization_code
#  keycloak:
#    realm: external
#    auth-server-url: http://localhost:8180/auth
#    resource: travel-assistant-client
#    credentials:
#      secret: 123123
#    public-client: true
#    ssl-required: none
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
#  pattern:
#    console: %d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n


